{
  "uid" : "119bda91a0988cea",
  "name" : "Test submenu and button on the Real-Time Decisioning page",
  "fullName" : "Test Redirection of Pages: Test submenu and button on the Real-Time Decisioning page",
  "historyId" : "96b67d630ca04692cbe842001ff5ca3a",
  "time" : {
    "start" : 1698835245673,
    "stop" : 1698835283215,
    "duration" : 37542
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a\"}\n  (Session info: headless chrome=114.0.5735.133); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559f51b744e3 <unknown>\n#1 0x559f518a3c76 <unknown>\n#2 0x559f518dfc96 <unknown>\n#3 0x559f518dfdc1 <unknown>\n#4 0x559f519197f4 <unknown>\n#5 0x559f518ff03d <unknown>\n#6 0x559f5191730e <unknown>\n#7 0x559f518fede3 <unknown>\n#8 0x559f518d42dd <unknown>\n#9 0x559f518d534e <unknown>\n#10 0x559f51b343e4 <unknown>\n#11 0x559f51b383d7 <unknown>\n#12 0x559f51b42b20 <unknown>\n#13 0x559f51b39023 <unknown>\n#14 0x559f51b071aa <unknown>\n#15 0x559f51b5d6b8 <unknown>\n#16 0x559f51b5d847 <unknown>\n#17 0x559f51b6d243 <unknown>\n#18 0x7f8712a90402 <unknown>\n\n",
  "statusTrace" : "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/PageRedirectionSteps.py\", line 103, in step_impl\n    button_element = context.driver.find_element(By.XPATH, xpath)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a\"}\n  (Session info: headless chrome=114.0.5735.133); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559f51b744e3 <unknown>\n#1 0x559f518a3c76 <unknown>\n#2 0x559f518dfc96 <unknown>\n#3 0x559f518dfdc1 <unknown>\n#4 0x559f519197f4 <unknown>\n#5 0x559f518ff03d <unknown>\n#6 0x559f5191730e <unknown>\n#7 0x559f518fede3 <unknown>\n#8 0x559f518d42dd <unknown>\n#9 0x559f518d534e <unknown>\n#10 0x559f51b343e4 <unknown>\n#11 0x559f51b383d7 <unknown>\n#12 0x559f51b42b20 <unknown>\n#13 0x559f51b39023 <unknown>\n#14 0x559f51b071aa <unknown>\n#15 0x559f51b5d6b8 <unknown>\n#16 0x559f51b5d847 <unknown>\n#17 0x559f51b6d243 <unknown>\n#18 0x7f8712a90402 <unknown>\n\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/PageRedirectionSteps.py\", line 103, in step_impl\n    button_element = context.driver.find_element(By.XPATH, xpath)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Given The user is on the \"live\" site",
      "time" : {
        "start" : 1698835246369,
        "stop" : 1698835274995,
        "duration" : 28626
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When The user hovers over the \"why-volt\" menu",
      "time" : {
        "start" : 1698835274996,
        "stop" : 1698835275480,
        "duration" : 484
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And The user clicks on the \"real_time_data\" submenu link and verify the redirection \"real_time_data\" page",
      "time" : {
        "start" : 1698835275481,
        "stop" : 1698835277667,
        "duration" : 2186
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When The user clicks on the \"it-to-the-next-level-live\" button",
      "time" : {
        "start" : 1698835277667,
        "stop" : 1698835283150,
        "duration" : 5483
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a\"}\n  (Session info: headless chrome=114.0.5735.133); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559f51b744e3 <unknown>\n#1 0x559f518a3c76 <unknown>\n#2 0x559f518dfc96 <unknown>\n#3 0x559f518dfdc1 <unknown>\n#4 0x559f519197f4 <unknown>\n#5 0x559f518ff03d <unknown>\n#6 0x559f5191730e <unknown>\n#7 0x559f518fede3 <unknown>\n#8 0x559f518d42dd <unknown>\n#9 0x559f518d534e <unknown>\n#10 0x559f51b343e4 <unknown>\n#11 0x559f51b383d7 <unknown>\n#12 0x559f51b42b20 <unknown>\n#13 0x559f51b39023 <unknown>\n#14 0x559f51b071aa <unknown>\n#15 0x559f51b5d6b8 <unknown>\n#16 0x559f51b5d847 <unknown>\n#17 0x559f51b6d243 <unknown>\n#18 0x7f8712a90402 <unknown>\n\n",
      "statusTrace" : "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/PageRedirectionSteps.py\", line 103, in step_impl\n    button_element = context.driver.find_element(By.XPATH, xpath)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "fbd704e7fb8f3522",
        "name" : "Error Message",
        "source" : "fbd704e7fb8f3522.txt",
        "type" : "text/plain",
        "size" : 988
      }, {
        "uid" : "28e5786dceef1e2b",
        "name" : "Screenshot of https://www.voltactivedata.com/real-time-data-processing/ Page",
        "source" : "28e5786dceef1e2b.png",
        "type" : "image/png",
        "size" : 1031454
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 2,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Then The user should be redirected to the \"it-to-the-next-level-live\" page",
      "time" : {
        "start" : 1698835283215,
        "stop" : 1698835283215,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When The user clicks on the \"to-meet-Market-needs-live\" button",
      "time" : {
        "start" : 1698835283215,
        "stop" : 1698835283215,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Then The user should be redirected to the \"to-meet-Market-needs-live\" page",
      "time" : {
        "start" : 1698835283215,
        "stop" : 1698835283215,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When The user clicks on the \"data-platforms-live\" button",
      "time" : {
        "start" : 1698835283215,
        "stop" : 1698835283215,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Then The user should be redirected to the \"data-platforms-live\" page",
      "time" : {
        "start" : 1698835283215,
        "stop" : 1698835283215,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 9,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "Test Redirection of Pages"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "119bda91a0988cea.json",
  "parameterValues" : [ ]
}